export const SET_CURRENT_PROJECT = 'SET_CURRENT_PROJECT'

export const DISPLAY_PROJECTS = 'DISPLAY_PROJECTS'

export const SET_CURRENT_VIDEO_TIME = 'SET_CURRENT_VIDEO_TIME'

export const RENDER_NOTE_FORM = 'RENDER_NOTE_FORM'

export const HIDE_NOTE_FORM = 'HIDE_NOTE_FORM'

export const ADD_NOTE = 'ADD_NOTE'

export const SET_CURRENT_USER = 'SET_CURRENT_USER'

export const FETCH_PROJECT = 'FETCH_PROJECT'

export const SET_VIDEO_PLAY_TIME = 'SET_VIDEO_PLAY_TIME'

export const LOG_OUT = 'LOG_OUT'

export const RENDER_NEW_PROJECT_FORM = 'RENDER_NEW_PROJECT_FORM'

export const RENDER_ADD_USER_TO_PROJECT_FORM = 'RENDER_ADD_USER_TO_PROJECT_FORM'
