export const SET_CURRENT_PROJECT = 'SET_CURRENT_PROJECT'

export const DISPLAY_PROJECTS = 'DISPLAY_PROJECTS'

export const SET_CURRENT_VIDEO_TIME = 'SET_CURRENT_VIDEO_TIME'

export const RENDER_NOTE_FORM = 'RENDER_NOTE_FORM'

export const HIDE_NOTE_FORM = 'HIDE_NOTE_FORM'

export const ADD_NOTE = 'ADD_NOTE'
