export const SET_CURRENT_PROJECT = 'SET_CURRENT_PROJECT'

export const DISPLAY_PROJECTS = 'DISPLAY_PROJECTS'

export const SET_CURRENT_VIDEO_TIME = 'SET_CURRENT_VIDEO_TIME'

export const RENDER_NOTE_FORM = 'RENDER_NOTE_FORM'

export const HIDE_NOTE_FORM = 'HIDE_NOTE_FORM'

export const ADD_NOTE = 'ADD_NOTE'

export const SET_CURRENT_USER = 'SET_CURRENT_USER'

export const FETCH_PROJECT = 'FETCH_PROJECT'

export const SET_VIDEO_PLAY_TIME = 'SET_VIDEO_PLAY_TIME'

export const LOG_OUT = 'LOG_OUT'

export const RENDER_NEW_PROJECT_FORM = 'RENDER_NEW_PROJECT_FORM'

export const RENDER_ADD_USER_TO_PROJECT_FORM = 'RENDER_ADD_USER_TO_PROJECT_FORM'

export const FAILED_TO_ADD_USER_TO_PROJECT = 'FAILED_TO_ADD_USER_TO_PROJECT'

export const SUCCESSFULLY_ADDED_USER_TO_PROJECT = 'SUCCESSFULLY_ADDED_USER_TO_PROJECT'

export const HIDE_ADD_USER_FORM = 'HIDE_ADD_USER_FORM'

export const HIDE_ADD_NOTE_FORM = 'HIDE_ADD_NOTE_FORM'

export const SHOW_COMMENTS = 'SHOW_COMMENTS'

export const HIDE_COMMENTS = 'HIDE_COMMENTS'

export const SET_COMMENTS = 'SET_COMMENTS'

export const ADD_COMMENT = 'ADD_COMMENT'

export const FETCHING_COMMENTS = 'FETCHING_COMMENTS'

export const TOGGLE_NOTE_COMPLETE = 'TOGGLE_NOTE_COMPLETE'

export const TOGGLE_COMPLETED_NOTE_DISPLAY =  'TOGGLE_COMPLETED_NOTE_DISPLAY'

export const HIDE_NEW_PROJECT_FORM = 'HIDE_NEW_PROJECT_FORM'
